<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeliveryOps.Application\DeliveryOps.Application.csproj" />
    <ProjectReference Include="..\DeliveryOps.Contracts\DeliveryOps.Contracts.csproj" />
    <ProjectReference Include="..\DeliveryOps.Domain\DeliveryOps.Domain.csproj" />
    <ProjectReference Include="..\DeliveryOps.Infrastructure\DeliveryOps.Infrastructure.csproj" />
  </ItemGroup>

</Project>
